name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: ['7.3', '7.4']

    steps:
    - uses: actions/checkout@v1

    - name: Validate
      run: composer validate

    - name: Install
      run: composer install --prefer-dist --no-progress

    - name: Test
      run: composer ci

    - uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
